# Generated by Django 5.1.2 on 2024-12-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavouritePositionSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_mm', models.IntegerField()),
                ('speed_mms', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('isPositionLost', models.BooleanField(default=False)),
                ('isOverloadProtectionUp', models.BooleanField(default=False)),
                ('isOverloadProtectionDown', models.BooleanField(default=False)),
                ('isAntiCollision', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('fav_height_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.favouritepositionsets')),
            ],
        ),
        migrations.CreateModel(
            name='FavPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_height', models.IntegerField()),
                ('fav_position_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_positions', to='home.favouritepositionsets')),
            ],
        ),
    ]
