# Generated by Django 4.2.16 on 2024-12-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Desk',
        ),
    ]
