# Generated by Django 5.1.2 on 2024-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='state_data',
        ),
        migrations.AlterField(
            model_name='desk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
