# Generated by Django 5.1.2 on 2024-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_controller', '0002_remove_desk_state_data_alter_desk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='state',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='desk',
            name='status',
            field=models.CharField(default='Normal', max_length=500),
        ),
    ]
