# Generated by Django 5.1.2 on 2025-01-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_controller', '0002_remove_desk_state_data_alter_desk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='state_data',
            field=models.JSONField(default=list),
        ),
    ]
