# Generated by Django 5.1.2 on 2025-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_controller', '0003_desk_state_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='state_data',
            field=models.JSONField(default=dict),
        ),
    ]
