# Generated by Django 4.2.17 on 2024-12-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deskuserprofile',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height1_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height2_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height3_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height4_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height5_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='height6_cm',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deskuserprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('desk_user', 'Desk User'), ('manager', 'Manager'), ('cleaner', 'Cleaner')], default='desk_user', max_length=20),
        ),
    ]
